services:
  db_mysql:
    container_name: mysql8
    image: mysql:8.4
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: FRANQUICIASDB
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456

volumes:
  mysql-data:
    external: false