server:
  port: 8001

spring.:
  application:
    name: msvc-franquicias

  webflux:
    base-path: /franquicias

db:
  database: FRANQUICIASDB
  host-name: mysql8
  max-size: 10
  max-live-connection: 60
  min-size: 5
  password: 123456
  port: 3306
  username: root